_commit: fdb71e3
_src_path: https://github.com/cvasilatos/python-template-project.git
description: Custom Logger
project_name: Decima Log
project_slug: decimalog
python_minor_version: 3.12.12
python_target_version: '312'
python_version: '3.12'
